// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: common_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Hunt.Common {

  /// <summary>Holder for reflection information generated from common_type.proto</summary>
  public static partial class CommonTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for common_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFjb21tb25fdHlwZS5wcm90bxILSHVudC5Db21tb24qPgoOQ29uZ2VzdGlv",
            "blR5cGUSDQoJQ09OX0xJR0hUEAASDgoKQ09OX05PUk1BTBABEg0KCUNPTl9I",
            "RUFWWRACKk8KClNlcnZlclR5cGUSCwoHU1RfTk9ORRAAEgsKB1NUX0dBTUUQ",
            "ARILCgdTVF9DSEFUEAISDAoIU1RfTE9HSU4QAxIMCghTVF9MT0NBTBAEYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Hunt.Common.CongestionType), typeof(global::Hunt.Common.ServerType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum CongestionType {
    [pbr::OriginalName("CON_LIGHT")] ConLight = 0,
    [pbr::OriginalName("CON_NORMAL")] ConNormal = 1,
    [pbr::OriginalName("CON_HEAVY")] ConHeavy = 2,
  }

  public enum ServerType {
    [pbr::OriginalName("ST_NONE")] StNone = 0,
    [pbr::OriginalName("ST_GAME")] StGame = 1,
    [pbr::OriginalName("ST_CHAT")] StChat = 2,
    [pbr::OriginalName("ST_LOGIN")] StLogin = 3,
    /// <summary>
    ///로컬 서버
    /// </summary>
    [pbr::OriginalName("ST_LOCAL")] StLocal = 4,
  }

  #endregion

}

#endregion Designer generated code
