// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: common_types.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Hunt.Common {

  /// <summary>Holder for reflection information generated from common_types.proto</summary>
  public static partial class CommonTypesReflection {

    #region Descriptor
    /// <summary>File descriptor for common_types.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonTypesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJjb21tb25fdHlwZXMucHJvdG8SC0h1bnQuQ29tbW9uKssBCgpQYWNrZXRU",
            "eXBlEgsKB0lOVkFMSUQQABIKCgZTWVNURU0QARINCglMT0dJTl9SRVEQAhIN",
            "CglMT0dJTl9BTlMQAxIUChBMT0dJTl9CWV9LRVlfUkVREAQSFAoQTE9HSU5f",
            "QllfS0VZX0FOUxAFEhcKE1JFVFVSTl9UT19MT0dJTl9SRVEQBhIXChNSRVRV",
            "Uk5fVE9fTE9HSU5fQU5TEAcSEwoOTE9HSU5fVEVTVF9SRVEQj04SEwoOTE9H",
            "SU5fVEVTVF9BTlMQkE4qbwoJRXJyb3JUeXBlEgsKB0VSUl9OT04QABIbChdF",
            "UlJfSU5WQUxJRF9QQUNLRVRfVFlQRRABEgoKBkVSUl9EQhACEhkKFUVSUl9B",
            "Q0NPVU5UX05PVF9FWElTVBADEhEKDUVSUl9EVVBfTE9HSU4QBCo+Cg5Db25n",
            "ZXN0aW9uVHlwZRINCglDT05fTElHSFQQABIOCgpDT05fTk9STUFMEAESDQoJ",
            "Q09OX0hFQVZZEAJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Hunt.Common.PacketType), typeof(global::Hunt.Common.ErrorType), typeof(global::Hunt.Common.CongestionType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum PacketType {
    [pbr::OriginalName("INVALID")] Invalid = 0,
    /// <summary>
    /// INVALID 패킷으로 통신된 경우, 내리는 패킷 타입 입니다.
    /// </summary>
    [pbr::OriginalName("SYSTEM")] System = 1,
    /// <summary>
    ///Login
    /// </summary>
    [pbr::OriginalName("LOGIN_REQ")] LoginReq = 2,
    /// <summary>
    /// 서버 응답
    /// </summary>
    [pbr::OriginalName("LOGIN_ANS")] LoginAns = 3,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("LOGIN_BY_KEY_REQ")] LoginByKeyReq = 4,
    [pbr::OriginalName("LOGIN_BY_KEY_ANS")] LoginByKeyAns = 5,
    [pbr::OriginalName("RETURN_TO_LOGIN_REQ")] ReturnToLoginReq = 6,
    [pbr::OriginalName("RETURN_TO_LOGIN_ANS")] ReturnToLoginAns = 7,
    [pbr::OriginalName("LOGIN_TEST_REQ")] LoginTestReq = 9999,
    [pbr::OriginalName("LOGIN_TEST_ANS")] LoginTestAns = 10000,
  }

  /// <summary>
  ///ErrType은 SYSTEM으로 
  /// </summary>
  public enum ErrorType {
    [pbr::OriginalName("ERR_NON")] ErrNon = 0,
    /// <summary>
    /// 잘못된 패킷 타입이 내려간경우
    /// </summary>
    [pbr::OriginalName("ERR_INVALID_PACKET_TYPE")] ErrInvalidPacketType = 1,
    /// <summary>
    ///DB에러가 뜬 경우, 스팀, mysql 등등...
    /// </summary>
    [pbr::OriginalName("ERR_DB")] ErrDb = 2,
    /// <summary>
    /// 로그인 - 계정이 없는 경우
    /// </summary>
    [pbr::OriginalName("ERR_ACCOUNT_NOT_EXIST")] ErrAccountNotExist = 3,
    /// <summary>
    ///중복 로그인인 경우
    /// </summary>
    [pbr::OriginalName("ERR_DUP_LOGIN")] ErrDupLogin = 4,
  }

  public enum CongestionType {
    [pbr::OriginalName("CON_LIGHT")] ConLight = 0,
    [pbr::OriginalName("CON_NORMAL")] ConNormal = 1,
    [pbr::OriginalName("CON_HEAVY")] ConHeavy = 2,
  }

  #endregion

}

#endregion Designer generated code
