// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: err_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Hunt.Common {

  /// <summary>Holder for reflection information generated from err_type.proto</summary>
  public static partial class ErrTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for err_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ErrTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5lcnJfdHlwZS5wcm90bxILSHVudC5Db21tb24qbwoJRXJyb3JUeXBlEgsK",
            "B0VSUl9OT04QABIbChdFUlJfSU5WQUxJRF9QQUNLRVRfVFlQRRABEgoKBkVS",
            "Ul9EQhACEhkKFUVSUl9BQ0NPVU5UX05PVF9FWElTVBADEhEKDUVSUl9EVVBf",
            "TE9HSU4QBGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Hunt.Common.ErrorType), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///ErrType은 SYSTEM으로 
  /// </summary>
  public enum ErrorType {
    [pbr::OriginalName("ERR_NON")] ErrNon = 0,
    /// <summary>
    /// 잘못된 패킷 타입이 내려간경우
    /// </summary>
    [pbr::OriginalName("ERR_INVALID_PACKET_TYPE")] ErrInvalidPacketType = 1,
    /// <summary>
    ///DB에러가 뜬 경우, 스팀, mysql 등등...
    /// </summary>
    [pbr::OriginalName("ERR_DB")] ErrDb = 2,
    /// <summary>
    /// 로그인 - 계정이 없는 경우
    /// </summary>
    [pbr::OriginalName("ERR_ACCOUNT_NOT_EXIST")] ErrAccountNotExist = 3,
    /// <summary>
    ///중복 로그인인 경우
    /// </summary>
    [pbr::OriginalName("ERR_DUP_LOGIN")] ErrDupLogin = 4,
  }

  #endregion

}

#endregion Designer generated code
