// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: msg_id.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Hunt.Common {

  /// <summary>Holder for reflection information generated from msg_id.proto</summary>
  public static partial class MsgIdReflection {

    #region Descriptor
    /// <summary>File descriptor for msg_id.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MsgIdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgxtc2dfaWQucHJvdG8SC0h1bnQuQ29tbW9uKvICCgVNc2dJZBILCgdJTlZB",
            "TElEEAASCgoGU1lTVEVNEAESDQoJTE9HSU5fUkVREAISDQoJTE9HSU5fQU5T",
            "EAMSFgoSTE9HSU5fQllfVE9LRU5fUkVREAQSFgoSTE9HSU5fQllfVE9LRU5f",
            "QU5TEAUSFAoQU0VMRUNUX1dPUkxEX1JFURAIEhQKEFNFTEVDVF9XT1JMRF9B",
            "TlMQCRIWChJDUkVBVEVfQUNDT1VOVF9SRVEQChIWChJDUkVBVEVfQUNDT1VO",
            "VF9BTlMQCxITCg9DUkVBVEVfQ0hBUl9SRVEQDBITCg9DUkVBVEVfQ0hBUl9B",
            "TlMQDRIUChBDT05GSVJNX05BTUVfUkVREA4SFAoQQ09ORklSTV9OQU1FX0FO",
            "UxAPEhIKDkNPTkZJUk1fSURfUkVREBASEgoOQ09ORklSTV9JRF9BTlMQERIT",
            "Cg5MT0dJTl9URVNUX1JFURCPThITCg5MT0dJTl9URVNUX0FOUxCQTmIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Hunt.Common.MsgId), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MsgId {
    [pbr::OriginalName("INVALID")] Invalid = 0,
    /// <summary>
    /// INVALID 패킷으로 통신된 경우, 내리는 패킷 타입 입니다.
    /// </summary>
    [pbr::OriginalName("SYSTEM")] System = 1,
    /// <summary>
    ///Login
    /// </summary>
    [pbr::OriginalName("LOGIN_REQ")] LoginReq = 2,
    /// <summary>
    /// 서버 응답
    /// </summary>
    [pbr::OriginalName("LOGIN_ANS")] LoginAns = 3,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("LOGIN_BY_TOKEN_REQ")] LoginByTokenReq = 4,
    [pbr::OriginalName("LOGIN_BY_TOKEN_ANS")] LoginByTokenAns = 5,
    [pbr::OriginalName("SELECT_WORLD_REQ")] SelectWorldReq = 8,
    [pbr::OriginalName("SELECT_WORLD_ANS")] SelectWorldAns = 9,
    [pbr::OriginalName("CREATE_ACCOUNT_REQ")] CreateAccountReq = 10,
    [pbr::OriginalName("CREATE_ACCOUNT_ANS")] CreateAccountAns = 11,
    [pbr::OriginalName("CREATE_CHAR_REQ")] CreateCharReq = 12,
    [pbr::OriginalName("CREATE_CHAR_ANS")] CreateCharAns = 13,
    [pbr::OriginalName("CONFIRM_NAME_REQ")] ConfirmNameReq = 14,
    [pbr::OriginalName("CONFIRM_NAME_ANS")] ConfirmNameAns = 15,
    [pbr::OriginalName("CONFIRM_ID_REQ")] ConfirmIdReq = 16,
    [pbr::OriginalName("CONFIRM_ID_ANS")] ConfirmIdAns = 17,
    [pbr::OriginalName("LOGIN_TEST_REQ")] LoginTestReq = 9999,
    [pbr::OriginalName("LOGIN_TEST_ANS")] LoginTestAns = 10000,
  }

  #endregion

}

#endregion Designer generated code
