// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum/Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Hunt.Enum {

  /// <summary>Holder for reflection information generated from Enum/Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum/Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9FbnVtL0VudW0ucHJvdG8SCUh1bnQuRW51bSpKCghBcHBseV9JRBIUChBB",
            "cHBseV9JRF9JTlZBTElEEAASEgoOQVBQTFlfQ09OU1RBTlQQCxIUChBBUFBM",
            "WV9QRVJDRU5UQUdFEAwqjwEKClRyaWdnZXJfSUQSFgoSVHJpZ2dlcl9JRF9J",
            "TlZBTElEEAASGAoUVFJJR0dFUl9ERUZBVUxUX1RBTEsQNBIYChRUUklHR0VS",
            "X1FVRVNUX0FDQ0VQVBA1EhQKEFRSSUdHRVJfQlVZX0lURU0QNhIfChtUUklH",
            "R0VSX0NIQU5HRV9ERUZBVUxUX1RBTEsQNyrAAgoHU3RhdF9JZBITCg9TdGF0",
            "X0lkX0lOVkFMSUQQABINCghTVEFUX0FUSxDoBxINCghTVEFUX0RFRhDpBxIM",
            "CgdTVEFUX0hQEOoHEgwKB1NUQVRfTVAQ6wcSEAoLU1RBVF9FTkVSR1kQ7AcS",
            "FgoRU1RBVF9GSUdIVF9TUElSSVQQ7QcSDQoIU1RBVF9BQ0MQ7gcSDQoIU1RB",
            "VF9FVkEQ7wcSDQoIU1RBVF9TUEQQ8AcSDgoJU1RBVF9KVU1QEPEHEhMKDlNU",
            "QVRfQ1JUQ0hBTkNFEPIHEhMKDlNUQVRfQ1JUREFNQUdFEPMHEhgKE1NUQVRf",
            "SU1fSFBfUkVDT1ZFUlkQ9AcSDQoIU1RBVF9BR0kQ9QcSDQoIU1RBVF9MVUsQ",
            "9gcSDQoIU1RBVF9TVFIQ9wcSDgoJU1RBVF9BU1BEEPgHKkkKCEdyb3VwX0lE",
            "EhQKEEdyb3VwX0lEX0lOVkFMSUQQABITCg1JVEVNX1JFQ09WRVJZEODUAxIS",
            "CgxJVEVNX0VORk9SQ0UQ8KIEKn4KC0NhdGVnb3J5X0lEEhcKE0NhdGVnb3J5",
            "X0lEX0lOVkFMSUQQABITCg5DQVRFR09SWV9HUk9VUBCQThIUCg5DQVRFR09S",
            "WV9VU0lORxCgnAESFwoRQ0FURUdPUllfUFJFQ0lPVVMQsOoBEhIKDENBVEVH",
            "T1JZX0VUQxDAuAIqZwoHUm9sZV9JRBITCg9Sb2xlX0lEX0lOVkFMSUQQABIX",
            "ChJST0xFX1FVRVNUX1BBWU1FTlQQmEMSGAoTUk9MRV9RVUVTVF9DT01QTEVU",
            "RRCZQxIUCg9ST0xFX1FVRVNUX0JPVEgQmkMqeAoIRXF1aXBfSUQSFAoQRXF1",
            "aXBfSURfSU5WQUxJRBAAEg4KCUVRVUlQX0hBVBCQAxIPCgpFUVVJUF9CT0RZ",
            "EJEDEhAKC0VRVUlQX0dMT1ZFEJIDEhAKC0VRVUlQX1NIT0VTEJMDEhEKDEVR",
            "VUlQX1dFQVBPThCUAypZCgZKb2JfSUQSEgoOSm9iX0lEX0lOVkFMSUQQABIL",
            "CgdKT0JfQUxMEGQSDwoLSk9CX1dBUlJJT1IQZRIOCgpKT0JfQVJDSEVSEGYS",
            "DQoJSk9CX0JPWEVSEGdCHFoaZ2l0aHViLmNvbS9IdW50L1RhYmxlO0h1bnRi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Hunt.Enum.Apply_ID), typeof(global::Hunt.Enum.Trigger_ID), typeof(global::Hunt.Enum.Stat_Id), typeof(global::Hunt.Enum.Group_ID), typeof(global::Hunt.Enum.Category_ID), typeof(global::Hunt.Enum.Role_ID), typeof(global::Hunt.Enum.Equip_ID), typeof(global::Hunt.Enum.Job_ID), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum Apply_ID {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("Apply_ID_INVALID")] Invalid = 0,
    /// <summary>
    ///상수
    /// </summary>
    [pbr::OriginalName("APPLY_CONSTANT")] ApplyConstant = 11,
    /// <summary>
    ///백분율
    /// </summary>
    [pbr::OriginalName("APPLY_PERCENTAGE")] ApplyPercentage = 12,
  }

  public enum Trigger_ID {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("Trigger_ID_INVALID")] Invalid = 0,
    /// <summary>
    ///기본 대사
    /// </summary>
    [pbr::OriginalName("TRIGGER_DEFAULT_TALK")] TriggerDefaultTalk = 52,
    /// <summary>
    ///퀘스트 수락 전 대사
    /// </summary>
    [pbr::OriginalName("TRIGGER_QUEST_ACCEPT")] TriggerQuestAccept = 53,
    /// <summary>
    ///아이템 구매 시 대사
    /// </summary>
    [pbr::OriginalName("TRIGGER_BUY_ITEM")] TriggerBuyItem = 54,
    /// <summary>
    ///NPC 변화 후 기본 대사
    /// </summary>
    [pbr::OriginalName("TRIGGER_CHANGE_DEFAULT_TALK")] TriggerChangeDefaultTalk = 55,
  }

  public enum Stat_Id {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("Stat_Id_INVALID")] Invalid = 0,
    /// <summary>
    ///공격력
    /// </summary>
    [pbr::OriginalName("STAT_ATK")] StatAtk = 1000,
    /// <summary>
    ///방어력
    /// </summary>
    [pbr::OriginalName("STAT_DEF")] StatDef = 1001,
    /// <summary>
    ///체력
    /// </summary>
    [pbr::OriginalName("STAT_HP")] StatHp = 1002,
    /// <summary>
    ///마나
    /// </summary>
    [pbr::OriginalName("STAT_MP")] StatMp = 1003,
    /// <summary>
    ///기력
    /// </summary>
    [pbr::OriginalName("STAT_ENERGY")] StatEnergy = 1004,
    /// <summary>
    ///투기
    /// </summary>
    [pbr::OriginalName("STAT_FIGHT_SPIRIT")] StatFightSpirit = 1005,
    /// <summary>
    ///명중률
    /// </summary>
    [pbr::OriginalName("STAT_ACC")] StatAcc = 1006,
    /// <summary>
    ///회피율
    /// </summary>
    [pbr::OriginalName("STAT_EVA")] StatEva = 1007,
    /// <summary>
    ///이동속도
    /// </summary>
    [pbr::OriginalName("STAT_SPD")] StatSpd = 1008,
    /// <summary>
    ///점프력
    /// </summary>
    [pbr::OriginalName("STAT_JUMP")] StatJump = 1009,
    /// <summary>
    ///치명타 확률
    /// </summary>
    [pbr::OriginalName("STAT_CRTCHANCE")] StatCrtchance = 1010,
    /// <summary>
    ///치명타 피해
    /// </summary>
    [pbr::OriginalName("STAT_CRTDAMAGE")] StatCrtdamage = 1011,
    /// <summary>
    ///체력 즉시 회복
    /// </summary>
    [pbr::OriginalName("STAT_IM_HP_RECOVERY")] StatImHpRecovery = 1012,
    /// <summary>
    ///민첩
    /// </summary>
    [pbr::OriginalName("STAT_AGI")] StatAgi = 1013,
    /// <summary>
    ///행운
    /// </summary>
    [pbr::OriginalName("STAT_LUK")] StatLuk = 1014,
    /// <summary>
    ///힘
    /// </summary>
    [pbr::OriginalName("STAT_STR")] StatStr = 1015,
    /// <summary>
    ///공격속도
    /// </summary>
    [pbr::OriginalName("STAT_ASPD")] StatAspd = 1016,
  }

  public enum Group_ID {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("Group_ID_INVALID")] Invalid = 0,
    /// <summary>
    ///회복류
    /// </summary>
    [pbr::OriginalName("ITEM_RECOVERY")] ItemRecovery = 60000,
    /// <summary>
    ///버프류
    /// </summary>
    [pbr::OriginalName("ITEM_ENFORCE")] ItemEnforce = 70000,
  }

  public enum Category_ID {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("Category_ID_INVALID")] Invalid = 0,
    /// <summary>
    ///장비류
    /// </summary>
    [pbr::OriginalName("CATEGORY_GROUP")] CategoryGroup = 10000,
    /// <summary>
    ///소비류
    /// </summary>
    [pbr::OriginalName("CATEGORY_USING")] CategoryUsing = 20000,
    /// <summary>
    ///귀중품류
    /// </summary>
    [pbr::OriginalName("CATEGORY_PRECIOUS")] CategoryPrecious = 30000,
    /// <summary>
    ///기타
    /// </summary>
    [pbr::OriginalName("CATEGORY_ETC")] CategoryEtc = 40000,
  }

  public enum Role_ID {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("Role_ID_INVALID")] Invalid = 0,
    /// <summary>
    ///퀘스트 지급자
    /// </summary>
    [pbr::OriginalName("ROLE_QUEST_PAYMENT")] RoleQuestPayment = 8600,
    /// <summary>
    ///퀘스트 완료자
    /// </summary>
    [pbr::OriginalName("ROLE_QUEST_COMPLETE")] RoleQuestComplete = 8601,
    /// <summary>
    ///지급 및 완료
    /// </summary>
    [pbr::OriginalName("ROLE_QUEST_BOTH")] RoleQuestBoth = 8602,
  }

  public enum Equip_ID {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("Equip_ID_INVALID")] Invalid = 0,
    /// <summary>
    ///투구
    /// </summary>
    [pbr::OriginalName("EQUIP_HAT")] EquipHat = 400,
    /// <summary>
    ///한벌옷
    /// </summary>
    [pbr::OriginalName("EQUIP_BODY")] EquipBody = 401,
    /// <summary>
    ///장갑
    /// </summary>
    [pbr::OriginalName("EQUIP_GLOVE")] EquipGlove = 402,
    /// <summary>
    ///신발
    /// </summary>
    [pbr::OriginalName("EQUIP_SHOES")] EquipShoes = 403,
    /// <summary>
    ///무기
    /// </summary>
    [pbr::OriginalName("EQUIP_WEAPON")] EquipWeapon = 404,
  }

  public enum Job_ID {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("Job_ID_INVALID")] Invalid = 0,
    /// <summary>
    ///공용
    /// </summary>
    [pbr::OriginalName("JOB_ALL")] JobAll = 100,
    /// <summary>
    ///전사
    /// </summary>
    [pbr::OriginalName("JOB_WARRIOR")] JobWarrior = 101,
    /// <summary>
    ///궁사
    /// </summary>
    [pbr::OriginalName("JOB_ARCHER")] JobArcher = 102,
    /// <summary>
    ///무투가
    /// </summary>
    [pbr::OriginalName("JOB_BOXER")] JobBoxer = 103,
  }

  #endregion

}

#endregion Designer generated code
